name: Build

on: workflow_dispatch

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rheuvel89/xamarin-container-action@v2
        with:
          SolutionPath: src/sample.Android/sample.Android.csproj
          ProjectPath: src/sample.sln
          SigningKeyStore: ${{ secrets.KEYSTORE }}
          SigningKeystorePassword: ${{ secrets.KEYSTORE_PASS }}
          SigningKeyAlias: ${{ secrets.KEY_ALIAS }}
          SigningKeyPassword: ${{ secrets.KEY_PASS }}
          BuildConfiguration: "Release"
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: build/**Signed.apk
