name: CI

on: 
   workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: |
          VERSION_NAME=$(sed -n 's/.*versionName\s*//p' ./app/build.gradle.kts | tr -d '"')
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

      - name: Print version
        run: echo "Version: ${{ env.VERSION_NAME }}"
