name: Android CI/cd

env:
  # 主模块仓库的名称
  main_project_module: app

  # Google Play 商店的名称
  playstore_name: Frogobox ID

on:
  # 在推送或拉取请求事件时触发工作流，但仅限于默认和受保护的分支
  workflow_dispatch:
  # 工作流将被调度到默认队列

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 设置当前日期作为环境变量
      - name: 设置当前日期作为环境变量
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # 设置仓库名称作为环境变量
      - name: 设置仓库名称作为环境变量
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # 请参见 '支持的发行版' 以获取可用选项
          java-version: '22'
          cache: 'gradle'

      - name: 更改 wrapper 权限
        run: chmod +x ./gradlew

      # 运行测试构建
      - name: 运行 gradle 测试
        run: ./gradlew test

      # 构建项目
      - name: 构建 gradle 项目
        run: ./gradlew build

      # 创建 APK 发布
      - name: 构建 APK 发布项目 (APK) - ${{ env.main_project_module }} 模块
        run: ./gradlew assemble

      - name: 构建的apk发表
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      
      - name: Get version
        id: get_version
        run: |
          VERSION_NAME=$(sed -n 's/.*versionName\s*//p' app/build.gradle | tr -d '"')
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
