name: Android Auto Build & Release

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # 设置超时时间

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 禁用凭据缓存

      - name: 设置文件权限
        run: |
          chmod +x gradlew  # 关键权限设置
          chmod -R +x ./signing || true  # 可选目录权限


      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |  # 缓存优化
            build.gradle.kts
            app/build.gradle.kts
            gradle/wrapper/gradle-wrapper.properties

      - name: 解析应用版本
        run: |
          VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | sed -E 's/.*"(.*)"/\1/')
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
          echo "::notice::构建版本：${VERSION_NAME}"

      - name: 运行 gradle 测试
        run: ./gradlew test

       # 解码 keystore
      - name: Save Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > key.keystore 2>/dev/null
        shell: bash


      # 读取签名配置
      - name: 读取签名配置
        run: |
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_ALIAS_PASSWORD=${{ secrets.KEY_ALIAS_PASSWORD }}" >> $GITHUB_ENV

      - name: 构建带签名的 APK
        run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=./key.keystore -Pandroid.injected.signing.store.password=${{ env.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ env.KEY_ALIAS }} -Pandroid.injected.signing.key.alias.password=${{ env.KEY_ALIAS_PASSWORD }}


      - name: 发布 Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION_NAME }}  
          name: sanyao ${{ env.VERSION_NAME }} Release
          body: |
            ### 构建信息
            - **构建时间**: ${{ env.BUILD_DATE }}
            - **提交版本**: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          draft: false
          prerelease: false
          files: ./app/build/outputs/apk/release/*.apk  
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
